name:               "灵感实验室"
favicon:            "/favicon.ico"
description:        "Inspiration Laboratory"
keywords:           "李昕亮, lixinliang, 互联网, 前端, html5, css3, javascript, nodejs"

url:                "http://www.lixinliang.com"
author:             "lixinliang"
introduce:          "不懂用户体验的技术不是好设计"
avatar:             "/image/avatar/01.jpg"

email:              "393464140@qq.com"
twitter:            "qq393464140"
github:             "lixinliang"
weibo:              "1736489187"
zhihu:              "qq393464140"

disqus_shortname:   "lixinliang"

background:         "/image/background/01.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Resume"
    href:           "/resume"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - README.md

keep_files:
  - presentation